-- MySQL Script generated by MySQL Workbench
-- lun. 03 avril 2017 11:56:35 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Epic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Epic` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Epic` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `idProject` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Epic_1_idx` (`idProject` ASC),
  CONSTRAINT `fk_Epic_1`
    FOREIGN KEY (`idProject`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Story`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Story` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Story` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `idEpic` BIGINT NOT NULL,
  `isActive` TINYINT(1) NULL,
  `description` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Story_1_idx` (`idEpic` ASC),
  CONSTRAINT `fk_Story_1`
    FOREIGN KEY (`idEpic`)
    REFERENCES `mydb`.`Epic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Task` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `process` VARCHAR(45) NULL,
  `results` VARCHAR(45) NULL,
  `parameters` VARCHAR(45) NULL,
  `idStory` BIGINT NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Task_1_idx` (`idStory` ASC),
  CONSTRAINT `fk_Task_1`
    FOREIGN KEY (`idStory`)
    REFERENCES `mydb`.`Story` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Status` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  `action` VARCHAR(45) NULL,
  `remarks` VARCHAR(45) NULL,
  `date` DATETIME NOT NULL,
  `idTask` BIGINT NOT NULL,
  `descriptionSprint` VARCHAR(45) NOT NULL,
  `descriptionVersion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Status_1_idx` (`idTask` ASC),
  CONSTRAINT `fk_to_task`
    FOREIGN KEY (`idTask`)
    REFERENCES `mydb`.`Task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project_has_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project_has_User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project_has_User` (
  `Project_idProject` BIGINT NOT NULL,
  `User_idUser` BIGINT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`Project_idProject`, `User_idUser`),
  INDEX `fk_Project_has_User_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Project_has_User_Project1_idx` (`Project_idProject` ASC),
  CONSTRAINT `fk_Project_has_User_Project1`
    FOREIGN KEY (`Project_idProject`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_has_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sprint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sprint` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sprint` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `number` INT NULL,
  `description` VARCHAR(45) NOT NULL,
  `idProject` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sprint_1_idx` (`idProject` ASC),
  CONSTRAINT `fk_Sprint_1`
    FOREIGN KEY (`idProject`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Version` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Version` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `description` VARCHAR(45) NOT NULL,
  `number` INT NULL,
  `idProject` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Version_1_idx` (`idProject` ASC),
  CONSTRAINT `fk_Version_1`
    FOREIGN KEY (`idProject`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
