-- MySQL Script generated by MySQL Workbench
-- ven. 31 mars 2017 12:04:35 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` LONG NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Epic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Epic` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Epic` (
  `id` LONG NOT NULL,
  `idProject` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Epic_1_idx` (`id` ASC),
  CONSTRAINT `fk_Epic_1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Story`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Story` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Story` (
  `id` LONG NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `idEpic` INT NOT NULL,
  `isActive` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Story_1_idx` (`id` ASC),
  CONSTRAINT `fk_Story_1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Epic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Task` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `id` LONG NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `process` VARCHAR(45) NULL,
  `results` VARCHAR(45) NULL,
  `parameters` VARCHAR(45) NULL,
  `idStory` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Task_1_idx` (`id` ASC),
  CONSTRAINT `fk_Task_1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Story` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sprint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sprint` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sprint` (
  `id` LONG NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `number` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Status` (
  `id` LONG NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  `remarks` VARCHAR(45) NULL,
  `date` DATETIME NOT NULL,
  `idTask` INT NOT NULL,
  `idSprint` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Status_1_idx` (`idTask` ASC),
  INDEX `fk_to_sprint_idx` (`idSprint` ASC),
  CONSTRAINT `fk_to_task`
    FOREIGN KEY (`idTask`)
    REFERENCES `mydb`.`Task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_to_sprint`
    FOREIGN KEY (`idSprint`)
    REFERENCES `mydb`.`Sprint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project_has_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project_has_User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project_has_User` (
  `Project_id` INT NOT NULL,
  `User_idr` INT NOT NULL,
  PRIMARY KEY (`Project_id`, `User_id`),
  INDEX `fk_Project_has_User_User1_idx` (`User_id` ASC),
  INDEX `fk_Project_has_User_Project1_idx` (`Project_id` ASC),
  CONSTRAINT `fk_Project_has_User_Project1`
    FOREIGN KEY (`Project_id`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_has_User_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StatusWatch`
-- -----------------------------------------------------
/*DROP TABLE IF EXISTS `mydb`.`StatusWatch` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StatusWatch` (
  `Status_idStatus` INT NOT NULL,
  `Task_idTask` INT NOT NULL,
  `Sprint_idSprint` INT NOT NULL,
  `date` DATETIME NULL,
  `action` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Status_idStatus`, `Task_idTask`, `Sprint_idSprint`),
  INDEX `fk_Status_has_Task_Task1_idx` (`Task_idTask` ASC),
  INDEX `fk_Status_has_Task_Status1_idx` (`Status_idStatus` ASC),
  INDEX `fk_StatusWatch_Sprint1_idx` (`Sprint_idSprint` ASC),
  CONSTRAINT `fk_Status_has_Task_Status1`
    FOREIGN KEY (`Status_idStatus`)
    REFERENCES `mydb`.`Status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Status_has_Task_Task1`
    FOREIGN KEY (`Task_idTask`)
    REFERENCES `mydb`.`Task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StatusWatch_Sprint1`
    FOREIGN KEY (`Sprint_idSprint`)
    REFERENCES `mydb`.`Sprint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;*/


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
